apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubey-api
  name: kubey-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: kubey-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubey-api
  name: kubey-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubey-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubey-api
    spec:
      containers:
        - image: quay.io/internetofsteve/kubey-api:latest
          imagePullPolicy: Always
          name: kubey-api
          readinessProbe:
            httpGet:
              path: /cowboyNames
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubey-api
spec:
  tls:
    - secretName: steve-dev-dius-cert
  rules:
  - host: 'steve.dev.dius.com.au'
    http:
      paths:
      - path: /cowboyNames
        backend:
          serviceName: kubey-api
          servicePort: 80